# Generated by Django 3.1.3 on 2021-03-04 19:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('acc_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('father', models.CharField(blank=True, max_length=100)),
                ('aadhar', models.CharField(max_length=12)),
                ('pan', models.CharField(max_length=10)),
                ('otp', models.CharField(blank=True, max_length=6)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
