# Generated by Django 3.1.3 on 2021-03-05 18:30

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210305_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.CharField(default='7878787878', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='aadhar',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='pan',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
