# Generated by Django 3.1.3 on 2021-03-16 07:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210305_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='current_balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(editable=False, max_length=3)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField(editable=False)),
                ('reciever', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='api.account')),
                ('sender', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='api.account')),
            ],
        ),
    ]
