# Generated by Django 3.1.3 on 2021-03-18 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210318_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
