# Generated by Django 3.1.6 on 2021-03-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='password',
            field=models.CharField(default='lundsssssss', max_length=50),
            preserve_default=False,
        ),
    ]
